[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
phf = { version = "0.11", features = ["macros"] }
pretty_assertions = "1.3.0"
rand = "0.8.5"
